meta:
  name: arch
  hostname: arch
spec:
  box: generic/ubuntu2004
  box_version: 3.2.2
  cores: 2
  ram: 2048
  vram: 32
provisioning:
  ssh_user: filwie
  ssh_private_key: '~/.ssh/id_rsa'
  ssh_public_key: '~/.ssh/id_rsa.pub'

  vars:
    git_user_name: filwie
    git_user_email: filip.wiechec@gmail.com
