meta:
  name: arch
  hostname: arch
spec:
  box: archlinux/archlinux
  box_version: 2020.08.12
  cores: 4
  ram: 4048
  vram: 128
provisioning:
  ssh_user: filwie
  ssh_private_key: '~/.ssh/id_rsa'
  ssh_public_key: '~/.ssh/id_rsa.pub'

  vars:
    git_user_name: filwie
    git_user_email: filip.wiechec@gmail.com
