---
- name: install packages
  package:
    name: '{{ arch_virtualization_packages[arch_virtualization_provider] }}'
    state: present
  become: true

- name: enable services
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  become: true
  loop: '{{ arch_virtualization_services[arch_virtualization_provider] }}'