---
- name: install packages
  package:
    name: '{{ arch_virtualization_packages[arch_virtualization_provider] }}'
    state: present
  become: true

- name: enable services
  systemd:
    name: '{{ item }}'
    state: started
    enabled: true
  become: true
  loop: '{{ arch_virtualization_services[arch_virtualization_provider] }}'

- name: create group
  group:
    name: '{{ item }}'
    state: present
  become: true
  loop: '{{ arch_virtualization_groups[arch_virtualization_provider] }}'

- name: add user to group
  user:
    name: '{{ ansible_user_id }}'
    groups: '{{ arch_virtualization_groups[arch_virtualization_provider] }}'
    append: true
  become: true
  notify: reset ansible connection