---
- name: template systemd services configs
  template:
    src: '{{ item }}.j2'
    dest: '/etc/systemd/{{ item }}'
  become: true
  notify: systemd daemon reload
  register: arch_network_service_config_result
  loop:
    - resolved.conf
    - timesyncd.conf

- name: start and enable services
  systemd:
    name: '{{ item }}'
    state: '{{ "restarted" if arch_network_service_config_result is changed else "started" }}'
    enabled: true
    daemon_reload: true
  become: true
  loop:
    - systemd-resolved
    - systemd-timesyncd