# vi: set ft=ruby :

VAGRANT_BOX = "archlinux/archlinux"
VAGRANT_HOSTNAME = "arch"
CPU_CORES = 2
MEMORY = 4048
VRAM = 64

repo_host = `git rev-parse --show-toplevel`
repo_vm = "/opt/ground-control]"

ANSIBLE_USER = "vagrant"
ANSIBLE_DIRECTORY = SYNC_DEST + "/ansible"
ANSIBLE_PLAYBOOK = "provision.yaml"

GITHUB_USERNAME = ENV["GITHUB_USERNAME"] || ""
GITHUB_TOKEN = ENV["GITHUB_TOKEN"] || ""

ANSIBLE_PLAYBOOK_TEARDOWN = ANSIBLE_DIRECTORY + "/teardown.yaml"
ANSIBLE_ARGS = ["-e github_username=" + GITHUB_USERNAME,
                "-e github_api_token=" + GITHUB_TOKEN]

Vagrant.configure("2") do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VAGRANT_HOSTNAME

  config.vm.synced_folder SYNC_SRC, SYNC_DEST

  config.vm.provider :virtualbox do |vbox|
    vbox.name = VAGRANT_HOSTNAME
    vbox.gui = false
    vbox.memory = MEMORY
    vbox.cpus = CPU_CORES
    vbox.customize ["modifyvm", :id, "--vram", VRAM]
    vbox.customize ["modifyvm", :id, "--accelerate3d", "on"]
    vbox.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # no python equals no Ansible
  config.vm.provision "shell", path: "../scripts/init.sh"

  config.vm.provision "ansible_local" do |ansible|
#    ansible.compatibility_mode = "2.0"
    ansible.playbook = ANSIBLE_PLAYBOOK
    ansible.provisioning_path = ANSIBLE_DIRECTORY
    ansible.extra_vars = {} ansible.raw_arguments = ANSIBLE_ARGS
    ansible.tags = ["github"]
    ansible.skip_tags = ["kvm"]
  end

  config.trigger.before :destroy do |trigger|
    trigger.info = "Running teardown playbook"
    trigger.run_remote = {
      inline: "sudo -u %s ansible-playbook %s -i %s/inventory $*" % [ANSIBLE_USER, ANSIBLE_PLAYBOOK_TEARDOWN, ANSIBLE_DIRECTORY],
      args: ANSIBLE_ARGS
    }
  end
end
