- name: install reflector
  package:
    name: reflector
    state: present
  become: true

- name: template reflector service and timer files
  template:
    src: '{{ item }}.j2'
    dest: '{{ arch_reflector_service_timer_dir }}/{{ item }}'
  become: true
  loop:
    - reflector.service
    - reflector.timer
  notify: systemd daemon reload
  register: arch_reflector_service_add_result

- meta: flush_handlers

- name: sort mirrors for the first time
  systemd:
    name: reflector.service
    state: started
    enabled: false
  become: true
  when: arch_reflector_service_add_result is changed

- name: start and enable reflector service timer
  systemd:
    name: reflector.timer
    state: started
    enabled: yes
  become: true
  notify: systemd daemon reload
  when: arch_reflector_enable_timer | bool