git_user_name: ''
git_user_email: ''

git_gitconfig_path: '~/.gitconfig'
git_core_excludesfile: '~/.gitignore_global'

git_aliases:
    - aliases: '!git config -l | grep alias | cut -c 7-'

git_core_editor: nvim
git_merge_tool: nvimdiff
git_diff_tool: nvimdiff
git_diff_tools:
    - name: nvimdiff
      cmd: nvim -d $BASE $LOCAL $REMOTE $MERGED -c '$wincmd w' -c 'wincmd J'
