# vi: set ft=ruby :

VAGRANT_API_VERSION = "2"
VAGRANT_BOX = "archlinux/archlinux"
VAGRANT_HOSTNAME = "arch"

ANSIBLE_PLAYBOOK = "../ansible/provision.yaml"
ANSIBLE_GROUP = "vagrant"
ANSIBLE_AS_ROOT = true

Vagrant.configure(VAGRANT_API_VERSION) do |config|
  config.vm.box = VAGRANT_BOX
  config.vm.hostname = VAGRANT_HOSTNAME
  config.vm.network "private_network", ip: "192.168.33.33"
  
  # config.vm.synced_folder "../data", "/data"
  
  config.vm.provider :virtualbox do |vbox|
    vbox.name = "arch"
    vbox.memory = 4048
    vbox.cpus = 2
  end
  
  # no python equals no Ansible
  config.vm.provision "shell", inline: "pacman -Sy --noconfirm python"
  
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = ANSIBLE_PLAYBOOK
    ansible.become = ANSIBLE_AS_ROOT
    ansible.extra_vars = {
      hosthname: "test01"
    }
  end
end
