---
- name: Import distribution-specific tasks
  include_tasks: '{{ ansible_distribution | lower }}.yml'
  when: ansible_distribution | lower in ['ubuntu', 'archlinux']

- name: Make sure prerequisites are installed
  package:
    name: "{{ neovim_prerequisites.packages }}"
  become: true

- name: Make sure Python modules are installed
  pip:
    name: "{{ neovim_prerequisites.python_modules }}"
    extra_args: --user
    executable: pip3

- name: Install Neovim
  package:
    name: neovim
  become: true
