---
- name: create separate user to build AUR packages
  user:
    name: '{{ arch_aur_builder_user }}'
    group: wheel
    create_home: true
    state: present
  become: true
  when: arch_aur_builder_user is defined

- name: allow AUR user to use pacman without providing password
  lineinfile:
    path: /etc/sudoers.d/aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: true
    validate: 'visudo -cf %s'
  become: true
  notify: reset connection

- meta: flush_handlers

- name: check if AUR helper is installed
  shell: 'command -v {{ arch_aur_helper }}'
  failed_when: false
  register: arch_aur_yay_command_result
  changed_when: false

- name: make sure dependencies are installed
  pacman:
    name: '{{ arch_aur_pacman_dependencies }}'
    state: present
  become: true
  when: arch_aur_yay_command_result.rc != 0

- name: clone AUR helper's repository
  git:
    repo: '{{ arch_aur_helper_git_repo_url }}'
    dest: '{{ arch_aur_helper_git_repo_path }}'
  register: arch_aur_helper_clone_result
  become: true
  become_user: '{{ arch_aur_builder_user }}'
  when: arch_aur_yay_command_result.rc != 0

- name: install AUR helper using makepkg
  command: makepkg --syncdeps --rmdeps --install --noconfirm
  args:
    chdir: '{{ arch_aur_helper_git_repo_path }}'
  become: true
  become_user: '{{ arch_aur_builder_user }}'
  when: arch_aur_yay_command_result.rc != 0
  async: 120
  poll: 5
