---
- hosts: localhost
  vars:
    required_packages:
      - git
      - gcc
      - g++
      - cmake
      - clang
    ccls_git_repo_url: https://github.com/MaskRay/ccls
    ccls_git_repo_path: /tmp/ccls
    ccls_cmake_cmd: cmake -H. -BRelease -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=
  tasks:
    - name: make sure required packages are installed
      package:
        name: "{{ required_packages }}"
        state: present
      become: true

    - name: clone ccls source code
      git:
        repo: "{{ ccls_git_repo_url }}"
        depth: 1
        recursive: true
        dest: "{{ ccls_git_repo_path }}"
        version: master

    - name: retrieve Clang resource directory
      command: clang -print-resource-dir
      register: clang_resource_dir_result

    - debug:
        msg: "{{ ccls_cmake_cmd }}{{ clang_resource_dir_result.stdout_lines[0] }}"

    - name: build ccls
      command: "{{ ccls_cmake_cmd }}{{ clang_resource_dir_result.stdout_lines[0] }}"
      args:
        chdir: "{{ ccls_git_repo_path }}"

