github_role_action: add

github_username: '{{ ansible_env.GITHUB_USERNAME }}'
github_api_token: '{{ ansible_env.GITHUB_TOKEN }}'

github_ssh_config: '{{ ansible_env.HOME }}/.ssh/config'
github_ssh_key_name: 'dev-{{ ansible_hostname }}'
github_ssh_key_algorithm: ed25519
github_ssh_private_key: '{{ ansible_env.HOME }}/.ssh/github_{{ github_ssh_key_algorithm }}'
github_ssh_public_key: '{{ github_ssh_private_key }}.pub'
