---
# If below variable is set to "rm", "remove" or "delete",
# the key will be removed from the account
github_role_action: add

github_username: '{{ ansible_env.GITHUB_USERNAME | default("") }}'
github_api_token: '{{ ansible_env.GITHUB_TOKEN | default("") }}'

github_ssh_config: '~/.ssh/config'
github_ssh_key_name: 'dev-{{ ansible_hostname }}'
github_ssh_key_algorithm: ed25519
github_ssh_private_key: '~/.ssh/github_{{ github_ssh_key_algorithm }}'
github_ssh_public_key: '{{ github_ssh_private_key }}.pub'
