---
- name: generate specified locales
  locale_gen:
    name: '{{ arch_locale_locale }}'
    state: present

- name: set locale
  command: localectl set-locale LANG={{ arch_locale_locale }}
  become: true

- name: set keyboard layout
  command: localectl set-keymap --no-convert {{ arch_locale_keyboard_layout }}
  become: true

- name: set timezone
  timezone:
    name: '{{ arch_locale_timezone }}'
  become: true