---
- name: check currently set locale
  shell: localectl | grep 'System Locale' | awk '{print $3}' | sed 's/LANG=//'
  register: arch_locale_locale_result
  changed_when: false

- name: generate specified locales
  locale_gen:
    name: '{{ arch_locale_locale }}'
    state: present
  when: arch_locale_locale_result != arch_locale_locale

- name: set locale
  command: localectl set-locale LANG={{ arch_locale_locale }}
  become: true
  when: arch_locale_locale_result.stdout != arch_locale_locale

- name: check currently set console keyboard layout
  shell: localectl | grep 'VC Keymap' | awk '{print $3}'
  register: arch_locale_vconsole_kb_result
  changed_when: false

- name: set console keyboard layout
  command: localectl set-keymap --no-convert {{ arch_locale_keyboard_layout }}
  become: true
  when: arch_locale_vconsole_kb_result.stdout != arch_locale_keyboard_layout

- name: set timezone
  timezone:
    name: '{{ arch_locale_timezone }}'
  become: true