---
- name: generate specified locales
  locale_gen:
    name: '{{ arch_locale_locale }}'
    state: present

- name: install dependencies for setting x11 keymap
  pacman:
    name: '{{ arch_locale_pacman_dependencies }}'
    state: present
  become: true

- name: set keyboard layout
  command: "{{ item }}"
  loop:
    - "localectl set-keymap --no-convert {{ arch_locale_keyboard_layout }}"
    - "localectl set-x11-keymap --no-convert {{ arch_locale_keyboard_layout }}"
  become: true