---
- block:
    - name: install xdg-user-dirs
      package:
        name: xdg-user-dirs
        state: present
      become: true

    - name: create xdg base directories
      file:
        path: '{{ item.path }}'
        state: directory
      loop: '{{ xdg_base_directory_spec.values() | list }}'

    - name: create xdg-user-dirs directories
      file:
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop: '{{ xdg_base_directory_user_dirs.values() | list }}'

    - name: template xdg-user-dirs config
      template:
        src: user-dirs.dirs.j2
        dest: "{{ ansible_env.HOME }}/.config/user-dirs.dirs"
      register: xdg_base_directory_config_result

    - name: update XDG directories
      command: xdg-user-dirs-update
      when:  xdg_base_directory_config_result is changed
  when:  ansible_distribution != 'MacOSX'

- name: update global shell configurations with xdg env vars
  blockinfile:
    path: '{{ item.path }}'
    block: '{{ item.block }}'
    create: true
  loop: '{{ xdg_base_directory_shell_files_blocks }}'
  become: true
  register: xdg_base_directory_shell_update_result

- meta: reset_connection
  when: xdg_base_directory_shell_update_result is changed
