---
- name: template systemd services configs
  template:
    src: '{{ item }}.j2'
    dest: '/etc/systemd/{{ item }}'
  become: true
  notify: systemd daemon reload
  register: arch_network_service_config_result
  loop:
    - resolved.conf
    - timesyncd.conf

- name: start and enable services
  systemd:
    name: '{{ item }}'
    state: '{{ "restarted" if arch_network_service_config_result is changed else "started" }}'
    enabled: true
    daemon_reload: true
  become: true
  loop:
    - systemd-resolved
    - systemd-timesyncd

- name: create symbolink link to /etc/resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    force: true
    state: link
  become: true

- name: NetworkManager
  block:

    - name: make sure dependencies are installed
      package:
        name: '{{ arch_network_dependencies }}'
        state: present

    - name: install network utilities
      package:
        name: '{{ arch_network_packages }}'
        state: present

  become: true
  when: arch_network_networkmanager

- name: NordVPN
  block:

    - name: create directory for NordVPN openvpn configs
      file:
        path: '{{ arch_network_nordvpn_openvpn_configs_dir }}'
        state: directory

    - name: download and unarchive NordVPN openvpn configs
      unarchive:
        src: '{{ arch_network_nordvpn_openvpn_configs_url }}'
        dest: '{{ arch_network_nordvpn_openvpn_configs_dir }}'
        remote_src: yes
        creates: '{{ arch_network_nordvpn_openvpn_configs_dir }}/ovpn_tcp/us-ca10.nordvpn.com.tcp.ovpn'

  when: arch_network_nordvpn
  become: true
