---
- name: clone dotfiles repository
  git:
    repo: '{{ dotfiles_repo_url }}'
    dest: '{{ dotfiles_repo_dest }}'
  register: dotfiles_clone_result

- name: run installation script
  command: '{{ dotfiles_install_script }}'
  when: dotfiles_clone_result is changed
