- name: install packages
  package:
    name: '{{ arch_sway_packages }}'
    state: present
  become: true

- name: create config directory if it is missing
  file:
    path: '{{ ansible_env.HOME }}/.config/sway'
    state: directory

- name: apply default config
  copy:
    src: '{{ arch_sway_conf_default }}'
    dest: '{{ arch_sway_conf }}'
    remote_src: true