---
- name: configure git
  block:
    - name: install git
      package:
        name: git
        state: present
      become: '{{ true if ansible_distribution != "MacOSX" else false }}'

    - name: template git config
      template:
        src: gitconfig.j2
        dest: '{{ git_gitconfig_path }}'

    - name: put global gitignore file in place
      copy:
        src: gitglobalignore
        dest: '{{ git_core_excludesfile }}'
        backup: true

