---
- name: check if bluetooth is available
  shell: dmesg | grep -i blue
  become: true
  register: arch_bluetooth_dmesg_result
  failed_when: false
  changed_when: false

- block:
  - name: install packages
    package:
      name: '{{ arch_bluetooth_packages }}'
      state: present
    become: true
    register: arch_bluetooth_packages_install_result

  - name: make sure required groups exists
    group:
      name: '{{ arch_bluetooth_group }}'
      state: present
    become: true

  - name: make sure user is in required groups
    user:
      name: '{{ ansible_user_id }}'
      groups:
        - '{{ arch_bluetooth_group }}'
    become: true
    notify: reset connection

  - name: enable specified group to use bluetooth without superuser privileges
    template:
      src: 51-blueman.rules.j2
      dest: '{{ arch_bluetooth_polkit_rules_file }}'
    become: true

  - name: start and enable bluetooth service
    systemd:
      name: bluetooth
      state: started
      daemon_reload: '{{ true if arch_bluetooth_packages_install_result is changed else false }}'
      enabled: true
    become: true
  when: arch_bluetooth_dmesg_result.rc == 0
