---
- name: create xdg base directories
  file:
    path: '{{ item }}'
    state: directory
  loop: '{{ xdg_spec.values() | list }}'
  tags: xdg.base-dirs

- name: xdg user directories
  block:
    - name: make sure xdg-user-dirs is installed
      package:
        name: xdg-user-dirs
        state: present
      become: true

    - name: make sure xdg-user-dirs directories exist
      file:
        path: '{{ item }}'
        state: directory
      loop: '{{ xdg_user_dirs.values() | list }}'
      when: item | length > 0

    - name: template xdg-user-dirs config
      template:
        src: user-dirs.dirs.j2
        dest: '{{ xdg_spec.XDG_CONFIG_HOME }}/user-dirs.dirs'

  when: ansible_system | default('') == 'Linux'
  tags: xdg.user-dirs

- name: update RC files of {{ xdg_rc_files_to_update | join(', ') }}
  blockinfile:
    path: '{{ xdg_rc_files[item].path[xdg_config_scope] }}'
    block: '{{ xdg_rc_files[item].block }}'
    create: true
  loop: '{{ xdg_rc_files.keys() | list }}'
  become: '{{ xdg_require_sudo }}'
  notify: reset connection
  tags: xdg.rc_files

- name: flush handlers
  meta: flush_handlers
