---
fonts_nerd_release_version: 'v2.0.0'
fonts_nerd_release_url: 'https://github.com/ryanoasis/nerd-fonts/releases/download/{{ fonts_nerd_release_version }}'
fonts_download_urls:
  - '{{ fonts_nerd_release_url }}/FantasqueSansMono.zip'
  - '{{ fonts_nerd_release_url }}/Iosevka.zip'
  - '{{ fonts_nerd_release_url }}/Mononoki.zip'

fonts_fontconfig_enable_presets:
  - 10-hinting-slight.conf
  - 10-sub-pixel-rgb.conf
  - 11-lcdfilter-default.conf
  - 70-no-bitmaps.conf
