---
fonts_directory: '{{ "~/Library/Fonts" if ansible_distribution == "MacOSX" else
                     ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + "/.local/share") + "/fonts" }}'
fonts_become_to_install_packages: '{{ false if ansible_distribution == "MacOSX" else true }}'

fonts_download_urls:
  - 'https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/3270.zip'
  - 'https://github.com/belluzj/fantasque-sans/releases/download/v1.7.2/FantasqueSansMono-Normal.zip'
  - 'https://github.com/be5invis/Iosevka/releases/download/v2.3.3/01-iosevka-2.3.3.zip'

fonts_fontconfig_enable_presets:
  - 10-hinting-slight.conf
  - 10-sub-pixel-rgb.conf
  - 11-lcdfilter-default.conf
  - 70-no-bitmaps.conf
