fonts_download_urls:
  - 'https://fontlibrary.org/assets/downloads/fantasque-sans-mono/b0cbb25e73a9f8354e96d89524f613e7/fantasque-sans-mono.zip'
  - 'https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-unhinted.zip'
  - 'https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-unhinted.zip'
  - 'https://noto-website-2.storage.googleapis.com/pkgs/NotoMono-hinted.zip'
  - 'https://github.com/be5invis/Iosevka/releases/download/v2.2.1/01-iosevka-2.2.1.zip'
  - 'https://github.com/madmalik/mononoki/releases/download/1.2/mononoki.zip'