---
- name: install packages
  package:
    name: '{{ docker_packages }}'
    state: present
  become: true

- name: enable docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: create docker group
  group:
    name: docker
    state: present
  become: true

- name: add users to group
  user:
    name: '{{ item }}'
    groups: docker
    append: true
  become: true
  notify: reset connection
  loop: '{{ docker_users }}'
