---
- hosts: all
  roles:
    - { name: arch_aur, tags: ['arch', 'aur'] }
    - { name: arch_bluetooth, tags: ['arch', 'bluetooth'] }
    - { name: arch_locale, tags: ['arch', 'locale'] }
    - { name: arch_network, tags: ['arch', 'network'] }
    - { name: arch_reflector, tags: ['arch', 'reflector'] }
    - { name: arch_sway, tags: ['arch', 'gui'] }
    - { name: git, tags: ['git'] }