---
- hosts: arch
  roles:
    - name: arch_locale
      tags: [arch, locale]
    - name: arch_reflector
      tags: [arch, reflector]
    - name: arch_network
      tags: [arch, network]
    - name: arch_aur
      tags: [arch, aur]
    - name: arch_bluetooth
      tags: [arch, bluetooth]
    - name: arch_virtualization
      tags: [arch, virtualization]
      # - name: arch_i3
      #   tags: [arch, i3, gui]
- hosts: all
  vars:
    github_role_action: add
  roles:
    - name: xdg_base_directory
      tags: xdg
    - name: terminal
      tags: terminal
    - name: dotfiles
      tags: dotfiles
    - name: github
      tags: github

