---
- hosts: all
  handlers:

    - name: reset ansible connection
      meta: reset_connection
      ignore_errors: true

  roles:

    - name: docker
      vars:
        docker_users:
          - '{{ ansible_user_id }}'
      tags: [docker]

    - name: git
      when: git_user_name and git_user_email
      tags: [git]

    - name: harbor
      vars:
        harbor_hostname: '{{ ansible_default_ipv4.address }}'
      tags: [harbor]
