---
- hosts: all
  handlers:

    - name: reset ansible connection
      meta: reset_connection
      ignore_errors: true

  vars:

    docker: true

  roles:

    - name: docker
      vars:
        docker_users:
          - '{{ ansible_user_id }}'
      when: docker
      tags: [docker]

    - name: git
      when: git_user_name and git_user_email
      tags: [git]
