---
- name: install packages
  package:
    name: '{{ terminal_packages }}'
  become: true

- name: create directories for vim-plug
  file:
    path: '{{ terminal_vim_plug_dest | dirname }}'
    state: directory

- name: install vim-plug
  get_url:
    url: '{{ terminal_vim_plug_download_url }}'
    dest: '{{ terminal_vim_plug_dest }}'
  tags: vim-plug

- name: install Tmux plugin manager
  git:
    repo: '{{ terminal_tpm_git_url }}'
    dest: '{{ terminal_tpm_dest }}'
  register: tmux_installation_result

- name: install Tmux plugins
  script: '{{ terminal_tpm_install_plugins_script }}'
  when: tmux_installation_result is changed

- name: install FZF
  block:
    - git:
        repo: '{{ terminal_fzf_git_url }}'
        dest: '{{ terminal_fzf_dest }}'
      register: fzf_clone_result

    - script: '{{ terminal_fzf_install_script }} --xdg --all'
      when: fzf_clone_result is changed
