---
- name: install packages
  package:
    name: '{{ terminal_packages }}'
  become: true

- name: create directories for vim-plug
  file:
    path: '{{ terminal_vim_plug_dest | dirname }}'
    state: directory

- name: install vim-plug
  get_url:
    url: '{{ terminal_vim_plug_download_url }}'
    dest: '{{ terminal_vim_plug_dest }}'
  tags: vim-plug

- name: install Tmux plugin manager
  git:
    repo: '{{ terminal_tpm_git_url }}'
    dest: '{{ terminal_tpm_dest }}'
  register: tmux_installation_result

- name: make sure Tmux plugin manager is enabled in Tmux config
  lineinfile:
    path: '{{ terminal_tmux_config }}'
    create: true
    line: "run '~/.tmux/plugins/tpm/tpm'"

- name: install Tmux plugins
  command: '{{ terminal_tpm_install_plugins_script }}'
  when: tmux_installation_result is changed

- block:
    - name: clone FZF repository
      git:
        repo: '{{ terminal_fzf_git_url }}'
        dest: '{{ terminal_fzf_dest }}'
        depth: 1
      register: fzf_clone_result

    - name: run FZF install script
      command: '{{ terminal_fzf_install_script }} --xdg --all'
      when: fzf_clone_result is changed
