---
- hosts: all
  vars:
    nfs_permitted_ips: '{{ ansible_env.NFS_PERMITTED_IPS | default("*") }}'
    nfs_exported_directory: '{{ ansible_env.NFS_EXPORTED_DIRECTORY | default("/mnt/nfs") }}'
    nfs_owner: '{{ ansible_env.NFS_OWNER | default("nfsnobody") }}'
    nfs_package: '{{ "nfs-utils" if ansible_distribution == "CentOS" else "nfs-common" }}'
  handlers:
    - name: Reload firewalld
      command: firewall-cmd --reload
      become: true
  tasks:
    - block:
        - name: Start and enable firewalld
          service:
            name: firewalld
            state: started
            enabled: true

        - name: Install nfs packages
          package:
            name: '{{ nfs_package }}'
            state: present

        - name: Create firewall rules for NFS
          firewalld:
            zone: public
            service: '{{ item }}'
            permanent: true
            state: enabled
          notify: Reload firewalld
          loop:
            - nfs
            - rpc-bind
            - mountd

        - name: Allow traffic to NFS ports
          firewalld:
            port: '{{ item }}'
            permanent: true
            state: enabled
          notify: Reload firewalld
          loop:
            - 2049/tcp
            - 2049/udp
            - 111/tcp
            - 111/udp

        - name: Create directory for NFS
          file:
            path: '{{ nfs_exported_directory }}'
            state: directory
            owner: '{{ nfs_owner }}'
            group: '{{ nfs_owner }}'
            mode: '777'

        - name: Start and enable nfs service
          systemd:
            name: nfs-server
            state: started
            enabled: true

        - name: Add directory to /etc/exports
          lineinfile:
            path: /etc/exports
            line: '{{ nfs_exported_directory }} {{ nfs_permitted_ips }}(no_root_squash,rw,sync)'
            regexp: '^{{ nfs_exported_directory }}.*'
            create: true
            backup: true
          register: add_directory_to_exports_result

        - name: Export directory
          command: exportfs -ra
          when: add_directory_to_exports_result is changed
      become: true
