base_box = "centos/7"
host_only_network_ip = ENV["NFS_SERVER_IP"] || "192.168.56.111"

nfs_enable = true
nfs_permitted_ips = ENV["NFS_PERMITTED_IPS"] || "*"
nfs_exported_directory = ENV["NFS_EXPORTED_DIRECTORY"] || "/mnt/nfs"
nfs_owner = ENV["NFS_OWNER"] || "nfsnobody"


Vagrant.configure("2") do |config|
  config.vm.box = base_box
  config.vm.network "private_network", ip: host_only_network_ip

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "2048"
  end

  if nfs_enable == true
    config.vm.provision "ansible" do |ansible|
      ansible.playbook = "nfs.yaml"
#      ansible.raw_arguments = ["-v"]
      ansible.extra_vars = {
        nfs_permitted_ips: nfs_permitted_ips,
        nfs_exported_directory: nfs_exported_directory,
        nfs_owner: nfs_owner
      }
    end
  end
end
