- name: check graphics card
  shell: lspci | grep -i 'vga\|3d\|2d' | cut -f 5- -d ' '
  register: x_check_graphics_card_result
  changed_when: false

- name: install Intel graphics driver
  package:
    name: '{{ item.driver }}'
    state: present
  become: true
  when: item.pattern in x_check_graphics_card_result.stdout
  loop: '{{ arch_x_graphics_drivers }}'

- name: install x-related packages
  package:
    name: '{{ arch_x_packages }}'
    state: present
  become: true

- name: set X11 keyboard layout
  command: localectl set-x11-keymap --no-convert {{ arch_x_keyboard_layout }}
  become: true
