- name: check graphics card
  shell: lspci | grep -i 'vga\|3d\|2d' | cut -f 5- -d ' '
  register: x_check_graphics_card_result
  changed_when: false

- name: install Intel graphics driver
  package:
    name: '{{ item.driver }}'
    state: present
  become: true
  when: item.pattern in x_check_graphics_card_result.stdout
  loop: '{{ arch_x_graphics_drivers }}'

- name: specify driver for Intel graphics card
  template:
    src: 20-intel.conf.j2
    dest: /etc/X11/xorg.conf.d/20-intel.conf
  become: true
  when: '"Intel" in x_check_graphics_card_result.stdout'

- name: install x-related packages
  package:
    name: '{{ arch_x_packages }}'
    state: present
  become: true

- name: check currently set x11 keyboard layout
  shell: localectl | grep 'X11 Layout' | awk '{print $3}'
  register: arch_x_kb_result
  changed_when: false

- name: set X11 keyboard layout
  command: localectl set-x11-keymap --no-convert {{ arch_x_keyboard_layout }}
  become: true
  when: arch_x_kb_result.stdout != arch_x_keyboard_layout
