xdg_data_home: '{{ ansible_env.XDG_DATA_HOME | default(ansible_env.HOME + "/.local/share") }}'

terminal_packages:
  - fish
  - git
  - highlight
  - ranger
  - ripgrep
  - rsync
  - tmux
  - tree
  - unzip
  - xclip
  - zsh
  - htop
  - iftop
  - iotop
  - neovim
  - terminfo
  - ncurses-devel
  - zsh

terminal_vim_plug_download_url: 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
terminal_vim_plug_dest: '{{ xdg_data_home + "/nvim/site/autoload/plug.vim"
                              if "neovim" in terminal_packages
                              else ansible_env.HOME + "/.vim/autoload/plug.vim" }}'

terminal_tmux_config: '{{ ansible_env.HOME }}/.tmux.conf'
terminal_tpm_git_url: 'https://github.com/tmux-plugins/tpm'
terminal_tpm_dest: '{{ ansible_env.HOME }}/.tmux/plugins/tpm'
terminal_tpm_install_plugins_script: '{{ terminal_tpm_dest }}/scripts/install_plugins.sh'

terminal_fzf_git_url: 'https://github.com/junegunn/fzf.git'
terminal_fzf_dest: '{{ xdg_data_home }}/fzf'
terminal_fzf_install_script: '{{ terminal_fzf_dest }}/install'
