---
- name: make sure SSH directory exists
  file:
    path: '~/.ssh'
    mode: 0700
    state: directory

- name: generate SSH keypair for GitHub
  openssh_keypair:
    path: '{{ github_ssh_private_key }}'
    type: '{{ github_ssh_key_algorithm }}'
  register: github_keypair_create_result
  tags: github::keypair

- name: '{{ github_role_action }} GitHub SSH key'
  github_key:
    name: '{{ github_ssh_key_name }}'
    token: '{{ github_api_token }}'
    pubkey: '{{ github_keypair_create_result.public_key }}'
    state: '{{ "absent" if github_role_action in ("rm", "remove", "delete")
               else "present" }}'
  tags: github::add_delete_key
  delegate_to: localhost

- name: specify which key to use for GitHub in SSH config
  blockinfile:
    path: '{{ github_ssh_config }}'
    create: true
    block: |
      Host GitHub
      Hostname github.com
      User git
      IdentityFile {{ github_ssh_private_key }}
  tags: github:ssh_config
