---
- name: gather os specific variables
  include_vars:
    file: '{{ "MacOSX.yaml" if ansible_distribution == "MacOSX" else "Linux.yaml" }}'

- name: make sure fontconfig and unzip are installed
  package:
    name: '{{ item }}'
    state: present
  become: '{{ fonts_become_to_install_packages }}'
  loop:
    - fontconfig
    - unzip

- name: create directory for fonts if it does not exist
  file:
    path: '{{ fonts_directory }}'
    state: directory

- name: download and unarchive fonts
  unarchive:
    src: '{{ item }}'
    dest: '{{ fonts_directory }}'
    remote_src: yes
    # TODO: tune below line
    creates: '{{ fonts_directory }}/mononoki-Regular.ttf'
  loop: '{{ fonts_download_urls }}'
  notify: update font cache
  register: fonts_download_result

- name: find files other than .ttf in fonts directory
  find:
    paths: '{{ fonts_directory }}'
    recurse: yes
    excludes: '*.ttf,.uuid'
    file_type: any
  register: fonts_directory_not_ttf_result
  when: fonts_download_result is changed

- name: remove found non-ttf files
  file:
    path: '{{ item.path }}'
    state: absent
  loop: '{{ fonts_directory_not_ttf_result.files }}'
  when: fonts_download_result is changed

- name: configure displaying of fonts
  file:
    src: '/etc/fonts/conf.avail/{{ item }}'
    dest: '/etc/fonts/conf.d/{{ item }}'
    state: link
  become: true
  loop: '{{ fonts_fontconfig_enable_presets }}'