---
- name: gather os specific variables
  include_vars:
    file: '{{ "MacOSX.yaml" if ansible_distribution == "MacOSX" else "Linux.yaml" }}'

- name: make sure fontconfig and unzip are installed
  package:
    name: '{{ item }}'
    state: present
  become: '{{ fonts_become_to_install_packages }}'
  loop:
    - fontconfig
    - unzip

- name: create directory for fonts if it does not exist
  file:
    path: '{{ fonts_directory }}'
    state: directory

- name: download and unarchive fonts
  unarchive:
    src: '{{ item }}'
    dest: '{{ fonts_directory }}'
    remote_src: yes
  loop: '{{ fonts_download_urls }}'
  notify: update font cache